### ISSUE TITLE
1GB sd card (non SDHC?) not loading BIOS

### ISSUE THREAD

**Issue by fanoush** [Basman74/Next186#2]
I am absolutely sure I wrote bios to last 8KB (16 sectors) of my 1GB microsd card but when booting it still says bios is not there. When using another 4GB SDHC card it works fine. Are cards below 4GB (= plain SD, not SDHC) supported?

**Comment by Basman74** [comment]
Hi Fanoush, 
No. It *must* be a SDHC card!
Cheers,Valentin 

    On Tuesday, 6 February 2018, 20:05, fanoush <notifications@github.com> wrote:
 

 I am absolutely sure I wrote bios to last 8KB (16 sectors) of my 1GB microsd card but when booting it still says bios is not there. When using another 4GB SDHC card it works fine. Are cards below 4GB (= plain SD, not SDHC) supported?—

**Comment by fanoush** [comment]
Well, typically DOS stuff does not need gigabytes of storage but OK, no problem. I'll check the source how hard it would be to add it. I sort of understand the reasons as SDHC is block oriented and a perhaps a bit easier to do, earlier SD is more of a mess.
